stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - scripts/preprocess.py
      - data/raw
    outs:
      - data/processed
  rank_dataset:
    cmd: python scripts/make_rank_dataset.py --horizon ${h}
    deps:
      - scripts/make_rank_dataset.py
      - data/processed
    outs:
      - data/ml/dataset_rank_${h}m.parquet
  train_ranker:
    cmd: python scripts/train_ranker.py --horizon ${h} --split ${split} --score_future
    deps:
      - scripts/train_ranker.py
      - data/ml/dataset_rank_${h}m.parquet
    outs:
      - data/ml/preds_rank_${h}m.parquet
    outs_no_cache:
      - artifacts/rank/ranker_${h}m_lgbm.pkl
